### PR TITLE
Add more type mappings and the title field

### PR DESCRIPTION
**Pull request by laughedelic**
This PR adds the `date`, `timestamp without time zone` and `numeric` types and the `title` field (as the capitalized column name).

### CODE REVIEW

**Comment by Qwerios** [comment]
Thanks for the pull request. Just need to change one thing because format for dates is `date-time`. 

Version 0.2.1 has been published to NPM

**Comment by laughedelic** [comment]
> Just need to change one thing because format for dates is date-time.

I'm not sure about that. The `date` type in PG is a date _without_ time.

From the [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6):

    full-date       = date-fullyear "-" date-month "-" date-mday
    full-time       = partial-time time-offset
    date-time       = full-date "T" full-time

So `date` should correspond to the `full-date`.

And then from the [JSON Schema spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1):

> Date and time format names are derived from RFC 3339, section 5.6 [RFC3339].
> 
> Implementations supporting formats SHOULD implement support for the following attributes:
> 
> * `date-time`: A string instance is valid against this attribute if it is a valid representation according to the "date-time" production.
> * `date`: A string instance is valid against this attribute if it is a valid representation according to the "full-date" production.
> * `time`: A string instance is valid against this attribute if it is a valid representation according to the "full-time" production.
> 
> Implementations MAY support additional attributes using the other production names defined in that section. **If "full-date" or "full-time" are implemented, the corresponding short form ("date" or "time" respectively) MUST be implemented, and MUST behave identically.**


So what we want for `date` is either `full-date` or (better) just `date`.

**Comment by Qwerios** [comment]
Agreed. I glanced over the fact it's date only. I stuck with the 'date' type from the JSON Schema spec.

New version published 0.2.2

**Comment by laughedelic** [comment]
Great, thanks!

**Pull request merged**
